version: '3.8'

services:
  
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: test123 
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar_user
      MYSQL_PASSWORD: traccar-secret
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  traccar:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: traccar-container
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_PORT: 3306
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar_user
      MYSQL_PASSWORD: traccar-secret
    ports:
      - "8082:8082" # Expose Traccar's default port (update if different)
    command: ["java", "-Xms1g", "-Xmx1g", "-Djava.net.preferIPv4Stack=true", "-jar", "tracker-server.jar", "conf/traccar.xml"]

volumes:
  mysql_data: