name: Build and push docker-compose images

env:
  DOCKERHUB_REPOSITORY: henokujuzi/enroute-core

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  docker-compose-build-push:
    name: Build and push docker-compose images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2
          curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set environment DOCKERHUB_IMAGE_TAGS on master
        run: echo "DOCKERHUB_IMAGE_TAGS=$DOCKERHUB_REPOSITORY:latest" >> $GITHUB_ENV

      - name: Set environment DOCKERHUB_IMAGE_TAGS
        if: github.ref != 'refs/heads/master'
        run: |
          _BRANCH=${GITHUB_REF##*/}
          _VERSION=${_BRANCH#v*}
          _MAJOR_VERSION=${_VERSION%.*}
          _DOCKERHUB_IMAGE_TAGS="$DOCKERHUB_REPOSITORY:$_VERSION-ubuntu"
          _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:$_MAJOR_VERSION-ubuntu"
          _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:ubuntu"
          _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:$_VERSION"
          _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:$_MAJOR_VERSION"
          echo "DOCKERHUB_IMAGE_TAGS=$_DOCKERHUB_IMAGE_TAGS" >> $GITHUB_ENV
      - name: Set environment DOCKERHUB_IMAGE_PLATFORMS
        run: |
          _DOCKERHUB_IMAGE_PLATFORMS="linux/amd64,linux/arm64"
          _DOCKERHUB_IMAGE_PLATFORMS+=",linux/arm/v7"
          echo "DOCKERHUB_IMAGE_PLATFORMS=$_DOCKERHUB_IMAGE_PLATFORMS" >> $GITHUB_ENV

      - name: Build and push docker-compose images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
