name: Build and push docker-compose images

env:
  DOCKERHUB_REPOSITORY: henokujuzi/enroute

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  docker-build-push:
    name: Build and push docker-compose images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment DOCKERHUB_IMAGE_TAGS on master
        if: github.ref == 'refs/heads/master'
        run: echo "DOCKERHUB_IMAGE_TAGS=$DOCKERHUB_REPOSITORY:latest" >> $GITHUB_ENV

      - name: Set environment DOCKERHUB_IMAGE_TAGS for versioned branches
        if: github.ref != 'refs/heads/master'
        run: |
          _BRANCH=${GITHUB_REF##*/}
          _VERSION=${_BRANCH#v*}
          _DOCKERHUB_IMAGE_TAGS="$DOCKERHUB_REPOSITORY:$_VERSION"
          echo "DOCKERHUB_IMAGE_TAGS=$_DOCKERHUB_IMAGE_TAGS" >> $GITHUB_ENV

      - name: Set environment DOCKERHUB_IMAGE_PLATFORMS
        run: |
          _DOCKERHUB_IMAGE_PLATFORMS="linux/amd64,linux/arm64"
          echo "DOCKERHUB_IMAGE_PLATFORMS=$_DOCKERHUB_IMAGE_PLATFORMS" >> $GITHUB_ENV

      - name: Build and push docker-compose images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker-compose.yml
          tags: ${{ env.DOCKERHUB_IMAGE_TAGS }}
          platforms: ${{ env.DOCKERHUB_IMAGE_PLATFORMS }}
          push: true
