name: Build and push docker-compose images

env:
  DOCKERHUB_REPOSITORY: henokujuzi/enroute

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  docker-compose-build-push:
    name: Build and push docker-compose images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker-compose images
        run: |
          # Build the images using docker-compose
          docker-compose -f docker-compose.yml build

          # Tag each service image and push to Docker Hub
          docker-compose -f docker-compose.yml push
